<a href="https://colab.research.google.com/github/lukwac123/machine_learning_bootcamp/blob/main/supervised/03_classification/07_naive_bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import sklearn

np.random.seed(42)
np.set_printoptions(precision=6, suppress=True)
sklearn.__version__

'1.6.1'

In [2]:
pogoda = ['słonecznie', 'deszczowo', 'pochmurno', 'deszczowo', 'słonecznie', 'słonecznie', 'pochmurno', 'pochmurno', 'słonecznie']
temperatura = ['ciepło', 'zimno', 'ciepło', 'ciepło', 'ciepło', 'umiarkowanie', 'umiarkowanie', 'ciepło', 'zimno']
spacer = ['tak', 'nie', 'tak', 'nie', 'tak', 'tak', 'nie', 'tak', 'nie']

raw_df = pd.DataFrame(data={'pogoda': pogoda, 'temperatura': temperatura, 'spacer': spacer})
df = raw_df.copy()
df

       pogoda   temperatura spacer
0  słonecznie        ciepło    tak
1   deszczowo         zimno    nie
2   pochmurno        ciepło    tak
3   deszczowo        ciepło    nie
4  słonecznie        ciepło    tak
5  słonecznie  umiarkowanie    tak
6   pochmurno  umiarkowanie    nie
7   pochmurno        ciepło    tak
8  słonecznie         zimno    nie

In [3]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df['spacer'] = encoder.fit_transform(spacer)
df

       pogoda   temperatura  spacer
0  słonecznie        ciepło       1
1   deszczowo         zimno       0
2   pochmurno        ciepło       1
3   deszczowo        ciepło       0
4  słonecznie        ciepło       1
5  słonecznie  umiarkowanie       1
6   pochmurno  umiarkowanie       0
7   pochmurno        ciepło       1
8  słonecznie         zimno       0

In [4]:
df = pd.get_dummies(df, columns=['pogoda', 'temperatura'], drop_first=True)
df

,spacer,pogoda_pochmurno,pogoda_słonecznie,temperatura_umiarkowanie,temperatura_zimno
0,1,False,True,False,False
1,0,False,False,False,True
2,1,True,False,False,False
3,0,False,False,False,False
4,1,False,True,False,False
5,1,False,True,True,False
6,0,True,False,True,False
7,1,True,False,False,False
8,0,False,True,False,True

In [5]:
data = df.copy()
target = data.pop('spacer')

data

,pogoda_pochmurno,pogoda_słonecznie,temperatura_umiarkowanie,temperatura_zimno
0,False,True,False,False
1,False,False,False,True
2,True,False,False,False
3,False,False,False,False
4,False,True,False,False
5,False,True,True,False
6,True,False,True,False
7,True,False,False,False
8,False,True,False,True

Klasyfikator bayesowski

In [6]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(data, target)

GaussianNB()

In [7]:
model.score(data, target)

0.7777777777777778

In [8]:
data.iloc[[0]]

,pogoda_pochmurno,pogoda_słonecznie,temperatura_umiarkowanie,temperatura_zimno
0,False,True,False,False

In [9]:
model.predict(data.iloc[[0]])

array([1])

In [10]:
encoder.classes_

array(['nie', 'tak'], dtype='<U3')

In [11]:
encoder.classes_[model.predict(data.iloc[[0]])[0]]

np.str_('tak')

In [12]:
model.predict_proba(data.iloc[[0]])

array([[0.000006, 0.999994]])