<a href="https://colab.research.google.com/github/lukwac123/machine_learning_bootcamp/blob/main/unsupervised/04_anomaly_detection/02_isolation_forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()

In [2]:
data = pd.read_csv('https://storage.googleapis.com/esmartdata-courses-files/ml-course/factory.csv')
data.head()

   item_length  item_width
0     6.206380    5.618286
1     5.756649    5.921924
2     5.576329    5.792401
3     5.304950    7.235000
4     6.764064    5.965792

In [3]:
data.describe()

       item_length  item_width
count   400.000000  400.000000
mean      5.824371    5.927004
std       1.040374    1.035379
min       0.117702    0.592448
25%       5.237362    5.410112
50%       5.907650    5.984139
75%       6.464539    6.513579
max       8.091519    8.365203

In [4]:
px.scatter(data, x='item_length', y='item_width', width=950, template='plotly_dark', title='Isolation Forest')

In [5]:
from sklearn.ensemble import IsolationForest

# contamination in [0, 0.05]
outlier = IsolationForest(n_estimators=100, contamination=0.05)
outlier.fit(data)

IsolationForest(contamination=0.05)

In [6]:
y_pred = outlier.predict(data)
y_pred[:30]

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [7]:
data['outlier_flag'] = y_pred
px.scatter(data, x='item_length', y='item_width', color='outlier_flag', width=950, template='plotly_dark',
           color_continuous_midpoint=-1, title='Isolation Forest')